[versions]
kotest = "5.5.5"
kotlin = "1.7.20"

[libraries]
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }

[bundles]
kotlin-testing = [
    "kotest-junit5-jvm",
    "kotest-assertions-core",
    "kotest-assertions-core-jvm"
]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
